devel/libthrift: update to 0.14.0
0.14.0 (2021-03-08)

C++

* THRIFT-1513 - Thrift compiler generates inconsistent code with some
  complex values (causing g++ to error: "has no member named '__isset')
* THRIFT-5168 - Useless generated code when .thrift file only has service type
* THRIFT-5179 - Thrift compiler will generate wrong code if IDL struct's
  name is 'a' or 'b'
* THRIFT-5200 - Thrift compiler will generate incorrect code when add
  'cob_style' option.
* THRIFT-4282 - StressTestNonBlocking is disabled in Appveyor as it is
  unstable on Windows in general
* THRIFT-4682 - C++ TBinaryProtocol crashes on port scan
* THRIFT-4963 - TNonblockingServer blocked int addTask(IOThread) and
  notify(workerThread)
* THRIFT-5047 - fix cmake support to build cpp server without OPENSSL
* THRIFT-5076 - Improve CMake OpenSSL usage
* THRIFT-5078 - Handle named pipe clients quickly disconnecting
* THRIFT-5086 - CMake target thrift::thrift has no
  INTERFACE_INCLUDE_DIRECTORIES property
* THRIFT-5110 - Added a number of required libs for using static OpenSSL
* THRIFT-5114 - Simplify the computation of the size of TMemoryBuffer
* THRIFT-5177 - getaddrinfo() should not be used for Unix sockets
* THRIFT-5178 - THttpClient should work without specifying host
* THRIFT-5185 - C++: Add WebSocket Server Transport
* THRIFT-5186 - AI_ADDRCONFIG: Thrift libraries crash with localhost-only
  network.
* THRIFT-5215 - C++: Remove portable_endian.h
* THRIFT-5217 - Deprecated boost header
* THRIFT-5237 - Implement MAX_MESSAGE_SIZE and consolidate limits into a
  TConfiguration class
* THRIFT-5290 - Adjusting cpp *.cproj msvcrt options according to LEGAL-538
* THRIFT-5295 - Thread and ThreadFactory should be extensible
* THRIFT-5344 - TTransport may throw raw pointer exceptions