Update libxml-ruby to 1.1.3.
== 1.1.3 / 2009-03-18 Charlie Savage

* Improve performance 10 to 20% by turning on libxml2's dictionary
  feature that allows parsers to reuse previously parsed strings.

* Fix XML::Node#remove! to work correctly with libxml's dictionary feature.

* Correctly set up parser context options.

* Simplify DOM modification code (Node#next=, Node#prev=, Node#sibling=) and
  update documenation.

* Deprecated Node#add_child and Node#child=, use Node#<< instead

* Fix documentation for Node#<<

* Added Document#import to enable moving nodes from one document
  to another document.


== 1.1.2 / 2009-03-12 Charlie Savage

* Added XML::Node#inner_xml helper method.

* Fix segmentation that could occur when calling the mark function on a
  previously freed node.

== 1.1.1 / 2009-03-10 Charlie Savage

* Fix - Only include extra html parser context methods for versions of libxml
  older than 2.6.27.

== 1.1.0 / 2009-03-09 Charlie Savage

* Fix bug caused by the mark function being called on partially initialized
  attributes.

* Revert back to libxml2's internal memory manager.

== 1.0.0 / 2009-03-05 Charlie Savage

* OS X (Charlie Savage).  Update bindings to support the default installed
  version of libxml2 (2.6.16) on OS X 10.5 and the latest version available
  via MacPorts.

== 0.9.9 / 2009-03-05 Charlie Savage

* Ruby 1.9.1 support (Charlie Savage). libxml-ruby now compiles and runs on eith
er
  1.8.6 and 1.9.1.  With 1.8.6 all tests should pass while on 1.9.1 all but
  for encoding tests pass.  The port to Ruby 1.9.1 revealed two memory
  allocation bugs (one with dtds, one with nodes) which are now fixed.

* Better OS X support (Joe Khoobyar).  The default version of libxml2
  on OS X 10.5 is fairly old, resulting in this link error:

    NSLinkModule() error
    dyld: Symbol not found: _htmlNewParserCtxt

  This can be fixed by using MacPorts to get a newer version of libxml2.
  To make use of MacPorts, the build script has been updated to use xml2-config.
  This can be fine-tuned using the new --with-xml2-config / --without-xml2-confi
g
  options to extconf.rb (default is  --without-xml2-config to match existing beh
avior).

* Greatly reduced memory usage (Joe Khoobyar).
  See http://rubyforge.org/pipermail/libxml-devel/2009-February/001375.html.

* Add Document#xhtml? and document#node_type methods (Joe Khoobyar)

* Add XPath::Object#last (Joe Khoobyar)

* Provide finer control over CDATA nodes on a parser by parser basis  (Joe Khoob
yar).

* Bug fix - Namespaces were incorrectly merged with attributes in the new sax2
  handler (Charlie Savage).

* Bug fix - Support iterating over nodes and attributes even with blocks
  that call remove! (Charlie Savage)

* Bug fix - If reader.node is NULL, return nil instead of crashing (Charlie Sava
ge)

* Bug fix - Dtd's owned by documents were freed twice in some circumstances (Joe
 Khoobyar).

* Bug fix - Fix output escaping on attributes nodes (Joe Khoobyar).

* Bug fix - Make sure IO objects are not garbage collected when used
  as parser sources (Charlie Savage).

== 0.9.8 / 2009-1-24 Charlie Savage

* Refactored XML::Parser, XML::HTMLParser, XML::SaxParser and
  XML::Reader to have consistent APIs.  All the parsers
  now take a context object in their constructors, allowing fine
  grained control over the parsers for advanced use cases.  These
  API changes are backwards compatible except
  for XML::Reader, which now takes an optional hash table as a
  second parameter in its various constructors versus an optional
  boolean value.

* Updated all APIs to use the encoding constants defined
  in XML::Encoding versus string values.  This API change
  is not backwards compatible.

* Added support for attribute declarations in DTD's via the new
  XML::AttrDecl class (Len Lattanzi)

* Support libxml's content escaping capabilities for text nodes by
  wrapping libxml's "xmlStringText" and "xmlStringTextNoenc"
  (Joe Khoobyar).

* Updated XML::Reader#read API to return true if a node was read,
  false if node was not read and raises an exception on an error.
  Previously #read returned 1 if a node was read, 0 if a node was
  not read and -1 for an error.  This change is not backwards
  compatible, but provides a more natural interface for Ruby by
  allowing code like this:

  while reader.read
    # do stuff
  end

* Changed XML::Error exception objects to return copies of nodes that
  cause parse errors instead of the original node.  This prevents
  segmentation faults when the error is reraised.

* Added XML::Reader#node method.

* Fixed compile errors on OS X which uses an older version of libxml.

* Fixed memory leak when performing XPath searches.

* Fixed rdocs.

* Don't override libxml's default settings for entity substitution and
  loading external DTDs.  This may break some code - you may need to
  add in a call to XML.default_substitute_entities = true or
  XML.default_load_external_dtd = true.

== 0.9.7 / 2008-12-08 Charlie Savage

* Added SAX2 support.  SAX handlers now define two new callbacks,
  on_start_element_ns and on_end_element_ns methods.  These
  new callbacks support namespaces, making them superior to the older
  callbacks on_start_element and on_end_element methods.  The old callbacks
  are still supported, but may be deprecated in the future depending
  on community feedback.

* Added SAX support for libxml's structured error handling.
  That menas sax handlers now define a new callback, on_error,
  which takes one parameter, an instance of XML::Error.  The older
  on_parser_error, on_parser_warning and on_parser_fatal_error
  callbacks are no longer suported so you must port your code.
  Note that the older callbacks took one string parameter, instead of
  an XML::Error object.

* Experimental work-around for libxml error handling bug - see
  http://mail.gnome.org/archives/xml/2008-December/msg00014.html
  for more information.

* Fix compilation bugs on Solaris.

* Fix Rdoc compilation bug.


== 0.9.6 / 2008-12-08 Charlie Savage

* Refactored namespace handling.  The existing, and inconsistent,
  namespace methods defined on XML::Node have been deprecated.
  They have been replaced by a the new XML::Namespaces class.
  Use this class to inspect a node's namespace, its default
  namespace, its namespace definitions and which namespaces
  are in scope.  It can be accessed via the the
  XML::Node#namespaces method.

* Rationalized XML::Document#save, XML::Document#to_s and
  XML::Node#to_s to take an optional hash table of parameters
  that control how output is generated. Supported parameters
  include setting indentation on or off, the indentation level
  and the output encoding.  This is an API change and may break
  existing calls to XML::Document#save.  However, the previous
  API was broken - setting the encoding resulted in an error so
  its unlikely anyone is using it.

* Rationalized XML::Document#debug, XML::Node#debug, XML::XPath::XPathObject#Deb
ug.

* Deprecated a number of duplicate dump* and debug_* methods in
  XML::Document and XML::Node.

* Additional Ruby 1.9.1 compatability fixes.

* Cleaned up header file guards.

== 0.9.5 / 2008-11-29 Charlie Savage

* Ruby 1.9.1 preview release compatability (Felipe Contreras)

* Update Node#remove! to return the removed node and to set
  its document to nil.  This allows the node to be either
  moved to another document, another part of the same document
  or to be freed on the next garbage collection once its
  references have gone out of scope.

* Fix bug where XPathExpression#compile mistakenly overwrote
  RegExp#compile.

* Update Node to use standard ruby allocators and initializers.

* Update HTML parser to be more forgiving of invalid documents.

* Update include paths for Darwin Ports on OS X.

* Updated C code base to use BSD/Allman style


== 0.9.4 / 2008-11-24 Charlie Savage

* Update HTML parser so that it can read files, strings and io
  streams.

* Update HTML parser to support user specified encodings.

* Additional C code cleanup.

== 0.9.3 / 2008-11-22 Charlie Savage

* Fixed segmentation fault caused by documents being freed
  before xpath results that referenced the document (take 2).

* Allowed sax parser to use io stream

* Combined encoding and input classes

* Cleaned up C code - removed remaining legacy structures,
  added static to most methods, changed C namespace from ruby_xml
  to rxml

== 0.9.2 / 2008-11-19 Charlie Savage

* Add support for compiled XPath expressions (donated by Pavel Valodzka)

* Fixes for compiling on OS X 10.5.4 and 10.5.5

== 0.9.1 / 2008-11-18 Charlie Savage

* Expose LibXML's encoding support via a new Encoding object.

* Revamp error handling to be much easier to use.  Errors are now
  wrapped by the new XML::Error class and are thrown as exceptions
  when it is appropriate.

* Fixed segmentation fault caused by documents being freed
  before xpath results that referenced the document.

* Add Node#register_default_namespace to simplify default namespace handling.

* Significantly improve documentation

* A number of bug fixes and patches.

== 0.9.0 / 2008-11-18 Charlie Savage

* Version 0.9.0 was removed due to packaging errors.