lang/gcc12: undefined reference to `__stack_chk_fail_local' errors
* Patch from NetBSD src. Fix -fPIC/-fPIE and -fstack-protector-strong/
  -fstack-protector-all causes undefined reference to `__stack_chk_fail_local'.
* This fixes a build of misc/libreoffice under NetBSD/i386 9 at least.
* Bump PKGREVISION.