devel/ruby-activesupport71: update to 7.1.4
Active Support 7.1.4 (2024-08-22)

* Improve compatibility for ActiveSupport::BroadcastLogger.
  (Máximo Mussini)

* Pass options along to write_entry in handle_expired_entry method.
  (Graham Cooper)

* Fix Active Support configurations deprecations.  (fatkodima)

* Fix teardown callbacks. (Tristan Starck)

* BacktraceCleaner silence core internal methods by default.
  (Jean Boussier)

* Fix delegate_missing_to allow_nil: true when called with implict self
  (Jean Boussier)

    class Person
      delegate_missing_to :address, allow_nil: true

      def address
	nil
      end

      def berliner?
	city == "Berlin"
      end
    end

    Person.new.city # => nil
    Person.new.berliner? # undefined local variable or method `city' for an instance of Person (NameError)

* Work around a Ruby bug that can cause a VM crash.  (Jean Boussier)

  This would happen if using TaggerLogger with a Proc formatter on
  which you called object_id.

    [BUG] Object ID seen, but not in mapping table: proc

* Fix ActiveSupport::Notifications.publish_event to preserve units.

  This solves the incorrect reporting of time spent running Active
  Record asynchronous queries (by a factor 1000).
  (Jean Boussier)