Update bomberclone to 0.11.9.
Changes:

Version 0.11.9
==============

- changed: opengamecache had to move to my own server. New address: ogc.gulpe.de:11111

- fixed: on certain networks, recvfrom hasen't returned. Even select
         returns with data aviable recvfrom got stuck because of no data.
         Added MSG_DONTWAIT here as flag. (only on linux)

- fixed: counter pkg_lastid became > 32767 almost messages are lost
         in cache managment
         patch from: Michel Bernay

- fixed: bug with selecting a player gfx.

- got a big patch file from Michel Bernay which fixes:
  fixed: bug about compute points of the winner in multiplayer mode
  fixed: bug for server for coputing point (Suppress all process in
         reception of playerdata)
  fixed: bug in cache managment (lot of messages lost by function
         rscachedel)
  added: function to find who player is owner of explosion to compute
         the killer
  added: function in debug for display player statistics
  changed: display points on general menu
  changed: scorring now a unique players wins a round add 1 point
           (bonus for victory) and numer of player killed by thge
           winner

- Added Warning if a game get startet with only one player selected
  Patch send in by: Carles Pina i Estany

- Added Joystick support - Patch send in by: Patrick Kirsch
  Chenges i made to the patch: I open only once the joystick device.
  Since after the patch the joystick got opened a few times without
  closing it again. The setupmenu will display now the number of the
  button which is selected for the function.

- Fixed BUG found by Lars Poeschel
  One player could join without problems and if a second player joined
  this network game, the server crashed in do_contest() accessing
  illegal memory. The problem is that a contest packet is received with
  to -1 and from 1. Then in the line
	players[ct_pkg->to].net.flags &= (0xFF - NETF_firewall);
  obviously illegal memory is accessed.
  Fixed the check of the to parameter from the contest packet. The
  server ignores now a to value of -1.


Version 0.11.8
================
14.12.2007

- Changed Docdir to $prefix/share/doc (Felipe Rafailov)

- Added some more resolutions. (requested by some users)

- Fixed BUG shown in: http://bugzilla.novell.com/show_bug.cgi?id=242031
  (patch from: Petr Gajdos)
  In network game i wanted to use all the time a different bomb
  instead of the first free aviable. In the code i forgot to modify
  some values. This patch should fix it now.
  (player.c:player_findfreebomb) changed i to nr.

- Fixed some drawing issues with flying bombs.

- The last special item use was lost on clients in a network game.
  special.use (was reset during special_clean)
  special.clean variable added to save the cleaning state.
      tested and works.

- Fixed: kicked bombs can travel in time. (map.bfield was set too early)
  rewrote full bomb kicked system.

- Fixed: compile warning: packets.c(635): error #592: variable "s_mod" is
  used before its value is set (reported by: David Binderman)

- Fixed: Special settings will be saved into the config file.

- Changed: all data will have thier own Makefile. So "make install" and
  "make dist" won't copy the CVS dirs.

- Fixed: Second Player Problem
  this fix includes that if a second player was used the game got somehow
  very instable, because there have been no reset of all the game data.
  playerselection works now much better. There have been problems with
  some keys for the second player.

- Fixed: problem on slow networks with the loop that the selected player
  gfx gots selected and deselected. (infinite loop on the network)

- Fixed: problem with overwriting the servers address on clients.
  problem only seen on server who gets connected from two differen ip
  addresses.