xentools415: update for pciutils 3.8.0
Untested because of

python3.10 ./scripts/ldnoexec.py out/rom16.o.strip.o out/rom16.noexec.o
Traceback (most recent call last):
  File "/scratch/sysutils/xentools415/work/seabios-rel-1.14.0/./scripts/ldnoexec.py", line 32, in <module>
    main()
  File "/scratch/sysutils/xentools415/work/seabios-rel-1.14.0/./scripts/ldnoexec.py", line 20, in main
    f = open(infilename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'out/rom32seg.o.strip.o'
gmake[6]: *** [Makefile:133: out/rom32seg.noexec.o] Error 1
gmake[6]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/scratch/sysutils/xentools415/work/seabios-rel-1.14.0/./scripts/ldnoexec.py", line 32, in <module>
    main()
  File "/scratch/sysutils/xentools415/work/seabios-rel-1.14.0/./scripts/ldnoexec.py", line 20, in main
    f = open(infilename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'out/rom16.o.strip.o'
gmake[6]: *** [Makefile:133: out/rom16.noexec.o] Error 1

on -current/amd64.

Run pkglint -F while here.