gnustep-back: fix linker problem
/usr/bin/ld: ./obj/gpbs.obj/gpbs.m.o: undefined reference to symbol '_Unwind_Resume'
/usr/bin/ld: /usr/pkg/lib/libunwind.so.1: error adding symbols: DSO missing from command line

by adding libunwind/bl3.mk and linking against it; for now only on NetBSD,
but feel free to make this unconditional.