qmail: mark as NOT_FOR_UNPRIVILEGED
Although the package itself builds when pkgsrc is bootstrapped in
unprivileged mode, the pkgsrc +INSTALL/+DEINSTALL scripts fail, causing
bulk build noise:

=> Creating binary package /wrk/mail/qmail/work/.packages/qmail-1.03nb49.tgz
fatal: unable to find user alias
===========================================================================

ERROR: instchown exited 111.

Permissions are likely wrong, and/or the queue may be uninitialized.

===========================================================================
pkg_add: install script returned error status
pkg_add: 1 package addition failed