(cad/klayout) Updated 0.29.2 to 0.29.4
0.29.4           (2024-07-08):
* Bug: %GITHUB%/issues/1780 Crash on deleting multiple selected shapes or items

0.29.3           (2024-07-06):
* Bug: %GITHUB%/issues/1774 ImportError: cannot import name '__version__' from 'klayout'
* Bug: %GITHUB%/issues/1771 Python exception formatting: backtrace missing for Python >=3.11.7
* Bug: %GITHUB%/issues/1757 Fixed memory issue
* Enhancement: %GITHUB%/issues/1756 Configure timeout for HTTP(S) requests
  A new environment variable has been introduced to configure the
  HTTP(S) timeout: KLAYOUT_HTTP_TIMEOUT (timeout value in seconds,
  default is 10s)
* Bug: %GITHUB%/issues/1769 Typo fixed
* Bug: %GITHUB%/issues/1751 Code sanity issue fixed
* Bug: %GITHUB%/issues/1750 Code sanity issue fixed
* Enhancement: %GITHUB%/issues/1747 Transformations on negative floats/ints
* Bug: %GITHUB%/issues/1743 strmxor shows no difference, klayout xor shows 85
* Enhancement: %GITHUB%/issues/1741 Tooltip strings for PCell parameters
* Bug: %GITHUB%/issues/1733 Instance selecion in object properties does not match with view port object highlight
* Enhancement: %GITHUB%/issues/1655 Marker object lifetime management
* Enhancement: DRC - step-wise size with "inside" and "outside" constraint
  This feature is handy for implementing latch-up rules more efficiently.
* Bugfix: OASIS reader - avoiding slight rounding of DBU In python read/write cycle (discussion-2526)
* Bugfix: Proper tracking of references of RecursiveShapeIterator.
  Related to issue #1742, but not directly.
* Bugfix: Symlinks in the salt paths might have lead to macro duplication
* Bugfix: Ruby binding - "return" inside block was behaving like "break".
  Now, "return" will leave the current function.
* Enhancement: LVS layer naming now also accepts an optional layer/datatype information.
* Enhancement: XOR performance enhanced in deep mode for "almost same" inputs.
* Bugfix: Macro debugger now does not prevent paint events and
  screen refresh should work while debugging. In addition, the debugger
  does not deadlock the desktop when using the help browser's search
  function. Side effects are yet unknown - maybe debugging Qt event
  handlers now becomes less stable.
  Issue #1770 addresses a problem introduced during this effort and also
  fixed in this release.
* Bugfix: During modal dialogs, the debugger's run/stop and step buttons were not working.
* Enhancement: DRC size/sized now also accepts sizing mode as string.
  For example "layer.sized(1.um, 'square_limit')" will work now.
  Previously, this argument has been ignored. This will make the GF180 DRC deck work properly.