syntax-highlighting: expects 64-bit atomic ops
We hit the usual issue, e.g., with i386:
definition.cpp:(.text+0x8c75): undefined reference to `__atomic_fetch_add_8'