Update to dovecot-1.0rc9.  From the release announcement mail:
Most importantly this should fix the login process problems that people
have been reporting. There were also some bugs in the proxying feature.

Also note the 64bit change in dovecot.index.cache files. Unless you
delete dovecot.index.cache files manually, you'll these kind of error
messages into your logs:

Error: Corrupted index cache file ...dovecot.index.cache:
registered field date.sent size changed

They'll get fixed automatically of course, but it might be a bit
annoying to see them.

	* 64bit systems: dovecot.index.cache file will be rebuilt because
	  some time fields have been changed from 64bit fields to 32bit
	  fields. Now the same cache file can be used in both 32bit and
	  64bit systems without it being rebuilt.
	* Added libmysqlclient workaround to conflicting sha1_result symbol,
	  which caused Dovecot to fail logging into MySQL.

	+ dovecot.index.cache file opening is delayed until it's actually
	  needed. This reduces disk accesses a bit with eg. STATUS commands.
	+ auth_cache: Try to handle changing passwords automatically: If
	  password verification fails, but the last one had succeeded, don't
	  use the cache. This works only with plaintext auth.
	- dovecot.index.cache: We didn't properly detect if some fields were
	  different length than we expected, which caused assert crashes
	- Lots of fixes to login/master process handling
	- mbox: Fixed a bug causing "X-IMAPbase uid-last unexpectedly lost
	  in mbox file" errors, and possibly others.