py-lsp-server: update to 1.7.2.
# History of changes

## Version 1.7.2 (2023/04/02)

### Issues Closed

- WorkDoneProgress tokens not initialized properly by the server
- yapf formatting fails when pyproject.toml is in the workspace

### Pull Requests Merged

- Add toml dependency for yapf and constrain yapf to be less than 0.32
- Raise upper bound of autopep8
- Bump pydocstyle to 6.3
- Initialize LSP progress token before using it and remove progress for sync plugins

----

## Version 1.7.1 (2023/01/17)

### Issues Closed

- Failed to load hook pylsp_lint: too many values to unpack (expected 3)

### Pull Requests Merged

- Use shlex.split() to split pylint flags
- Improve Jedi file completions for directories
- Include missing Pylint "information" category
- Add top constraint to Pylint and fix constraint for `whatthepatch`
- Fix pydocstyle linting with its 6.2.0 version
- Use `sys.executable` instead of `python` in Pylint plugin

----

## Version 1.7.0 (2022/12/29)

### New features

* Add a new plugin to provide autoimport functionality (disabled by default).
* Add progress reporting.
* Make `jedi_definition` plugin follow definitions to `pyi` files.
* Add support for flake8 version 6.
* Add support for Yapf ignore patterns.
* Add mccabe setting to flake8 plugin.

### Issues Closed

- Is there a configuration option to enable jumping to builtin module stubs
- Autoimport keep throwing exception when delete a line
- `textDocument/documentSymbol` returns empty result for non-existing files
- List of allowed values for pylsp.plugins.pydocstyle.convention in CONFIGURATION.md incorrect
- Progress support
- Auto-import

### Pull Requests Merged

- Don't show signature for modules in hovers
- Change Pylint run to set cwd correctly
- Expose setting to follow builtin and extension definitions to stub files
- Fix Pycodestyle linting with line endings other than LF
- Ensure proper document match to avoid empty outline (Symbols)
- Support Flake8 version 6
- Update Readme with link to python-lsp-ruff and mention to code actions
- Make flake8 respect configuration
- Fix autoimport raising AttributeError in some cases
- Fix the completion of `include_function_objects`
- Report autoimport progress
- Fix symbols for non-existing (unsaved) files
- Fix autoimport plugin not being disabled by default
- Update outdated username in docs
- Update allowed values for pydocstyle convention in CONFIGURATION.md
- Fix Debian package name
- Add progress reporting
- Add a plugin to provide autoimport functionality
- Add mccabe setting to flake8
- Add support for Yapf ignore patterns

----

## Version 1.6.0 (2022/11/02)

### New features

* Migrate to MarkupContent and convert docstrings to Markdown by default.
* Add support for flake8 version 5.
* Add function objects to Jedi completions.
* Don't include class and functions objects by default in Jedi completions.

### Issues Closed

- Completion result have "typeParameter" duplicates
- Server warns when optional modules do not exist
- Errors in CONFIGURATION.md
- Conflict between README and CONFIGURATION
- Add alternative ways to install python-lsp-server
- Add function objects to completions
- `Failed to load hook pylsp_completions: 'NoneType' object has no attribute 'type'` when working with Numpy 1.23
- Consider using docstring_to_markdown for markdown hover and documentation
- Migrate from deprecated MarkedString to MarkupContent

### Pull Requests Merged

- Don't include class objects by default in completions
- Improve how Jedi handles Numpy
- Make default for `include_function_objects` false
- Include params only for classes and functions
- Update the configuration schema for consistency
- Prefer info log message for missing optional modules
- Fix options not being passed to yapf format
- PR: Include all symbols that Jedi reports as declared in a file when `add_import_symbols` is `False`
- Fix pylint message in tests
- Add support for flake8 version 5
- Include traceback when plugin fails to load
- Add more installation instructions to Readme
- Add support for including function objects
- Remove redundant wheel dep from pyproject.toml
- Update release instructions to use new build mechanism
- Migrate to MarkupContent and convert docstrings to Markdown

----

## Version 1.5.0 (2022/07/10)

### New features

* Add `DiagnosticTag` tags for Pylint, Pycodestyle, and Flake8 plugins.
* Add support to connect to the server through websockets.
* Allow multiple per-file-ignores for the same pattern in Flake8 plugin.
* Parse YAPF diffs into TextEdits.
* Add support for LSP formatting `options` parameter.

### Issues Closed

- Flake8 reports wrong severity level for code Fxxx
- Flake8 reports wrong severity level for E999
- Add .flake8 to the discovery paths
- Rope completions enabled or disabled by default
- Please add basic usage documentation
- Add `DiagnosticTag` tags for pylint, pycodestyle, and flake8
- Flake8 plugins issues
- Websockets built-in support

### Pull Requests Merged

- Report Flake8 errors with Error severity level
- Fix documentation for location of Flake8 configuration files
- Use Numpy less than 1.23 in our tests
- Add `DiagnosticTag` support
- Improve schema type compliance, improve CONFIGURATION.md
- Add autopep8.enabled to the configuration schema
- Change severity level for flake8 errors
- Remove preload module from Readme
- Allow multiple per-file-ignores for the same pattern in flake8 plugin
- Remove reference to pyls-flake8 in Readme
- Restore the copyright headers in `setup.cfg` and `pyproject.toml`
- Match rope_completions setting documentation with reality
- Move the project metadata into `PEP 621`-compliant `pyproject.toml`
- Add plugins for pylint and flake8 to readme
- Mention `pylsp` command in README
- Fix section that was misplaced in changelog
- Parse YAPF diffs into TextEdits (instead of sending the full doc)
- Add support for LSP formatting `options` parameter
- Add web sockets support

----

## Version 1.4.1 (2022/03/27)

### Pull Requests Merged

- Fix Yapf formatting with CRLF line endings
- Improved documentation regarding configuration

----

## Version 1.4.0 (2022/03/11)

### New features

* Support pycodestyle indent-size option
* Add `DiagnosticTag` constants from LSP 3.15
* Drop support for Python 3.6

### Issues Closed

- Plugin crash crashes whole diagnostic
- README.md: Windows users trying to install the *extras* in `cmd.exe` need to use double quotes instead of single quotes
- C extensions printing on import break pylint diagnostics
- Still shows diagnostics on closed files
- Use git-based versioning

### Pull Requests Merged

- Clear diagnostics when closing documents
- Update single quotes to double quotes for install command examples
- Prevent third-party plugins with faulty hooks to crash the server
- Prevent faulty third-party plugins to crash the server
- Fix Autopep8 and Yapf formatting with CR line endings
- Fix pygame greeting breaking pylint diagnostics
- Add `DiagnosticTag` constants from LSP 3.15
- Support pycodestyle indent-size option
- Make pylint test Python version independent
- Add license info to `setup.py` so it will show up in wheel installs
- Update Python base version to 3.7+
- Move the package metadata from setup.py to setup.cfg

----

## Version 1.3.3 (2021-12-13)

### Issues Closed

- Resolving completion triggers an error

### Pull Requests Merged

- Fix test_syntax_error_pylint_py3 for Python 3.10
- Fix error when resolving completion items for Rope

----

## Version 1.3.2 (2021-11-25)

### Issues Closed

- Error on triggering completions in import context

### Pull Requests Merged

- Fix formatting a log message

----

## Version 1.3.1 (2021-11-22)

### Pull Requests Merged

- Fix tests for Jedi 0.18.1

----

## Version 1.3.0 (2021-11-22)

### New features

* Create a cache for code snippets to speed up completions.

### Important changes

* Option `jedi_completion.resolve_at_most_labels` was renamed to `jedi_completion.resolve_at_most`
  because now it controls how many labels and snippets will be resolved per request.
* Option `jedi_completion.cache_labels_for` was renamed to `jedi_completion.cache_for` because now
  it controls the modules for which labels and snippets should be cached.
* Update requirements on Pylint, flake8, pycodestyle, pyflakes and autopep8.

### Pull Requests Merged

- Fix another test with Python 3.10
- Use sys.executable in flake8 plugin to make tests pass on systems that don't provide a python link
- Fix test with Python 3.10
- Update requirements on flake8 and its dependencies
- Adjust readme to pylsp-mypy rename
- Unpin Pylint
- Create a cache for snippets