Update mlterm to 3.1.6.
Changes from 3.1.4 (per doc/en/ReleaseNote):

ver 3.1.6
* Support ":[Percentage]" format for font-fb.
  (e.g. ISO8859_1=/../font.pcf:100)
* Support gzipped pcf fonts in framebuffer.
* Support 3 byte rgb color sequence.
  (<ESC>[38;2;<r>;<g>;<b>m and <ESC>[48;2;<r>;<g>;<b>m)
* Support DECCRA(<ESC>[...$v) and DECERA(<ESC>[...$z).
* Add --altbuf / "use_alt_buffer" option which is equivalent to
  "titeInhibit" of xterm.
* Add --colors / "use_ansi_colors" option which is equivalent to
  "colorMode" of xterm.
* Add --exitbs / "exit_backscroll_by_pty" option.
* -Y option converts unicode line drawing characters (U+2500 etc) to dec
  special ones in order to show them correctly with a unicode font which
  contains double-width glyphs or no glyphs for line characters.
* Update unicode property table (generated from UnicodeData.txt and
  EastAsianWidth.txt) to version 6.2.0.
* "blink_cursor" option is available for libvte.
* Remove "add_picture" and "remove_picture" commands from configuration
  protocol, and add "show_picture" command to it.
* Change key sequences in term_type=mlterm
  (application cursor key mode is off)
  XK_HOME: \x1bOH -> \x1b[H   XK_END : \x1bOF -> \x1b[F
* Change key seuqences in term_type=rxvt.
  (application cursor key mode is off)
  XK_HOME: \x1b[7~ -> \x1b[H  XK_END : \x1b[8~ -> \x1b[F
  (application cursor key mode is on)
  XK_HOME: \x1bOH -> \x1b[7~  XK_END : \x1bOF -> \x1b[8~
* Bug fixes:
  Fix the bug of showing incorrect glyphs of large fonts like unifont.pcf.
  Fix the infinite loop in the failure of executing the command specified with -e option.
  Fix the compilation error in linking gdk-pixbuf-2.0. (SF topic #6234829)
  (Thanks to Lotus Shih and rabin_y)
  Fix the bug of incorrect input of 'A' - 'Z' keys in win32.
  Fix the memory leak of scrollbar views.

ver 3.1.5
* Support framebuffer on Linux. (Experimental)
  (See doc/en/README.fb or doc/ja/README.fb in detail.)
* Support "?" of OSC 4, 10 and 11.
* Support CSI 14 t and CSI 18 t.
* Break the binary compatility of extra scrollbars and pixmap_engine
  with the ones before 3.1.4.
* Add "update_all" to the configuration protocol.
* Add k5 entry for ~/.mlterm/termcap.
* Bug fixes:
  Fix the incomplete hebavior of double- or triple-clicking and dragging.
  (Thanks to Andi Cristian Serbanescu)