Update to Asterisk 13.15.0.  This is mostly a bug fix release with a few minor enhancements.  13.14.1 was released to fix AST-2017-001.
----- 13.15.0

The Asterisk Development Team would like to announce the release of
Asterisk 13.15.0.

The release of Asterisk 13.15.0 resolves several issues reported by the
community and would have not been possible without your participation.

*Thank you!*

The following issues are resolved in this release:

*New Features made in this release:*
-----------------------------------
- [ASTERISK-26878 <https://issues.asterisk.org/jira/browse/ASTERISK-26878>]
- func_channel: Add ability to get the callid so dialplan has access to it.
(Reported by Richard Mudgett)
- [ASTERISK-26863 <https://issues.asterisk.org/jira/browse/ASTERISK-26863>]
- res_pjsip: Add endpoint identification scheme based on a configured SIP
header/value
(Reported by Matt Jordan)
- [ASTERISK-17428 <https://issues.asterisk.org/jira/browse/ASTERISK-17428>]
- [patch] Allow "Comedian Mail" branding to be removed
(Reported by John Covert)

*Bugs fixed in this release:*
-----------------------------------
- [ASTERISK-26851 <https://issues.asterisk.org/jira/browse/ASTERISK-26851>]
- res_pjsip_sdp_rtp: RTP instance does not use same IP as explicit transport
(Reported by Richard Begg)
- [ASTERISK-26897 <https://issues.asterisk.org/jira/browse/ASTERISK-26897>]
- chan_sip: Security vulnerability with client code header
(Reported by Alex Villacís Lasso)
- [ASTERISK-26916 <https://issues.asterisk.org/jira/browse/ASTERISK-26916>]
- res_pjsip: Excessive refcount reached on transport ao2 object
(Reported by Ross Beer)
- [ASTERISK-26705 <https://issues.asterisk.org/jira/browse/ASTERISK-26705>]
- libasteriskssl.so not found when asterisk is installed for the 1st time
(Reported by George Joseph)
- [ASTERISK-26850 <https://issues.asterisk.org/jira/browse/ASTERISK-26850>]
- res_hep_pjsip: Asterisk insert wrong protocol name in "Protocol ID" field
in HEP packets
(Reported by Max Norba)
- [ASTERISK-26484 <https://issues.asterisk.org/jira/browse/ASTERISK-26484>]
- res_pjsip_messaging: Crash when using invalid URI in MessageSend 'from'
argument.
(Reported by Vinod Dharashive)
- [ASTERISK-26776 <https://issues.asterisk.org/jira/browse/ASTERISK-26776>]
- res_pjsip_pubsub: Crash when generating xpidf content
(Reported by Andrew Green)
- [ASTERISK-26880 <https://issues.asterisk.org/jira/browse/ASTERISK-26880>]
- Asterisk crashes when multiple speex users join confbridge with pp_vad
and dtx enabled
(Reported by Kirsty Tyerman)
- [ASTERISK-26862 <https://issues.asterisk.org/jira/browse/ASTERISK-26862>]
- app_queue: Queue stops calling members with local interface after
forwarding in previous call
(Reported by Robert Mordec)
- [ASTERISK-26732 <https://issues.asterisk.org/jira/browse/ASTERISK-26732>]
- res_rtp_asterisk: Implement RTCP Multiplexing - breaking WebRTC in Chrome
(Reported by Dan Jenkins)
- [ASTERISK-26879 <https://issues.asterisk.org/jira/browse/ASTERISK-26879>]
- PJSIP external_media_address ignored if no local_net options are provided
(Reported by Matt Jordan)
- [ASTERISK-26867 <https://issues.asterisk.org/jira/browse/ASTERISK-26867>]
- autochan: Locking in a function ast_autochan_destroy() on destroyed
channel (after masquerade).
(Reported by Krzysztof Trempala)
- [ASTERISK-26869 <https://issues.asterisk.org/jira/browse/ASTERISK-26869>]
- res_pjsip_refer: blind call transfer w/o a user name doesn't go to the s
extension
(Reported by Torrey Searle)
- [ASTERISK-26668 <https://issues.asterisk.org/jira/browse/ASTERISK-26668>]
- core: Malformed pattern matching extension (various factors) results in
crash
(Reported by xrobau)
- [ASTERISK-26865 <https://issues.asterisk.org/jira/browse/ASTERISK-26865>]
- chan_iax2: Reload of iax peer results in loss of host address/port
(Reported by Richard Begg)
- [ASTERISK-26872 <https://issues.asterisk.org/jira/browse/ASTERISK-26872>]
- Bundled pjproject fails to build when tarball downloaded with curl due to
md5 verification failure in Docker containers (or when there is no terminal)
(Reported by Matt Jordan)
- [ASTERISK-26717 <https://issues.asterisk.org/jira/browse/ASTERISK-26717>]
- Document the fact that Asterisk HEP support only works with the PJSIP
channel driver
(Reported by Olivier Krief)
- [ASTERISK-26643 <https://issues.asterisk.org/jira/browse/ASTERISK-26643>]
- Extra new line in Device field of DeviceStateChange AMI Event after
restart of Asterisk
(Reported by Roman Bedros)
- [ASTERISK-25237 <https://issues.asterisk.org/jira/browse/ASTERISK-25237>]
- stasis_cache.c:845 caching_topic_exec: - misleading ERROR message
(Reported by Smirnov Aleksey)
- [ASTERISK-26857 <https://issues.asterisk.org/jira/browse/ASTERISK-26857>]
- chan_pjsip: Dialplan function race condition
(Reported by Joshua Colp)
- [ASTERISK-26841 <https://issues.asterisk.org/jira/browse/ASTERISK-26841>]
- chan_sip: Call not cancelled after receiving a 422 response
(Reported by Jean Aunis - Prescom)
- [ASTERISK-26822 <https://issues.asterisk.org/jira/browse/ASTERISK-26822>]
- pjsip/cli_commands: pjsip show channelstats shows wrong codec
(Reported by Kevin Harwell)
- [ASTERISK-26685 <https://issues.asterisk.org/jira/browse/ASTERISK-26685>]
- res_pjsip: Crash when using IPv6 and Transport ws,wss
(Reported by Michael Balen)
- [ASTERISK-24562 <https://issues.asterisk.org/jira/browse/ASTERISK-24562>]
- app_voicemail: Cannot set fromstring on a per-mailbox basis
(Reported by Mark Scholten)
- [ASTERISK-26598 <https://issues.asterisk.org/jira/browse/ASTERISK-26598>]
- Saynumber is trying to get "and" from "digits/" subfolder
(Reported by Jonathan Harris)
- [ASTERISK-17067 <https://issues.asterisk.org/jira/browse/ASTERISK-17067>]
- Long lines in call files cause spurious syntax error
(Reported by Dave Olszewski)
- [ASTERISK-26796 <https://issues.asterisk.org/jira/browse/ASTERISK-26796>]
- res_pjsip_transport_websocket: Via header is 'WS' when it should be 'WSS'
(Reported by Jørgen H)
- [ASTERISK-25628 <https://issues.asterisk.org/jira/browse/ASTERISK-25628>]
- res_config_pgsql: should match the behavior of other drivers so that
queue_log can disable adaptive logging
(Reported by Dmitry Wagin)
- [ASTERISK-26825 <https://issues.asterisk.org/jira/browse/ASTERISK-26825>]
- pjsip.conf.sample: user_agent: still refers to branch 12
(Reported by Tzafrir Cohen)
- [ASTERISK-26823 <https://issues.asterisk.org/jira/browse/ASTERISK-26823>]
- PJSIP: Persistent subscriptions can cause FRACKs if endpoint does not
exist
(Reported by Mark Michelson)
- [ASTERISK-26623 <https://issues.asterisk.org/jira/browse/ASTERISK-26623>]
- res_pjsip: Crash when calling PJSIPShowEndpoint
(Reported by Jørgen H)
- [ASTERISK-26808 <https://issues.asterisk.org/jira/browse/ASTERISK-26808>]
- res_pjsip_outbound_registration doesn't know about network change events
(Reported by George Joseph)
- [ASTERISK-26313 <https://issues.asterisk.org/jira/browse/ASTERISK-26313>]
- chan_sip : Asterisk restart seems to be required for changing encryption
option
(Reported by benasse)
- [ASTERISK-26781 <https://issues.asterisk.org/jira/browse/ASTERISK-26781>]
- bridge: Passing the 'p' (play tone) flag to Bridge() application results
in garbled audio
(Reported by Sean Bright)
- [ASTERISK-26782 <https://issues.asterisk.org/jira/browse/ASTERISK-26782>]
- res_pjsip: URI requirement for fields is not consistently documented and
error does not provide indication
(Reported by Peter Sokolov)
- [ASTERISK-26812 <https://issues.asterisk.org/jira/browse/ASTERISK-26812>]
- [patch] Fix download_externals To Allow The Use Of curl Or wget
(Reported by Michael L. Young)
- [ASTERISK-18271 <https://issues.asterisk.org/jira/browse/ASTERISK-18271>]
- Pattern matching with res_config_mysql extensions does not behave as
expected
(Reported by Charlie Smurthwaite)
- [ASTERISK-26669 <https://issues.asterisk.org/jira/browse/ASTERISK-26669>]
- PJSIP Segfault 13.13.1 (Bundled PJSIP)
(Reported by Nic Colledge)
- [ASTERISK-18731 <https://issues.asterisk.org/jira/browse/ASTERISK-18731>]
- [patch] DUNDi weight parameter not processed correctly
(Reported by Peter Racz)
- [ASTERISK-26580 <https://issues.asterisk.org/jira/browse/ASTERISK-26580>]
- [patch] Error during LDAP modify action when user unregisters
(Reported by Nicholas John Koch)
- [ASTERISK-26799 <https://issues.asterisk.org/jira/browse/ASTERISK-26799>]
- res_pjsip: Using an auth object for inbound and outbound authentication
fails.
(Reported by Richard Mudgett)
- [ASTERISK-26738 <https://issues.asterisk.org/jira/browse/ASTERISK-26738>]
- Frequent segfaults since activation of DNS SRV, in
pjsip_auth_clt_reinit_req at /pjsip/sip_auth_client.c, and
pj_atomic_inc_and_get at pj/os_core_unix.c
(Reported by Michael Maier)
- [ASTERISK-25893 <https://issues.asterisk.org/jira/browse/ASTERISK-25893>]
- Function vmauthenticate accesses uninitialized memory
(Reported by Filip Jenicek)
- [ASTERISK-26802 <https://issues.asterisk.org/jira/browse/ASTERISK-26802>]
- [patch] Integrity Check Of PJSIP Download Fails
(Reported by Michael L. Young)
- [ASTERISK-15858 <https://issues.asterisk.org/jira/browse/ASTERISK-15858>]
- [patch] Fix query with double backslash in string literals and stop log
warnings
(Reported by Humberto Figuera)
- [ASTERISK-26057 <https://issues.asterisk.org/jira/browse/ASTERISK-26057>]
- res_config_sqlite3 uses incorrect query - unnecessary escape
(Reported by Stepan)
- [ASTERISK-23457 <https://issues.asterisk.org/jira/browse/ASTERISK-23457>]
- SQlite3: Realtime queue loading fails after PRAGMA query result
(Reported by Scott Griepentrog)
- [ASTERISK-26794 <https://issues.asterisk.org/jira/browse/ASTERISK-26794>]
- http: Crash on Reload Only in ast_tcptls_server_start
(Reported by Joshua Elson)
- [ASTERISK-26714 <https://issues.asterisk.org/jira/browse/ASTERISK-26714>]
- Phone default have not ringing on ARM
(Reported by Igor Goncharovsky)
- [ASTERISK-26696 <https://issues.asterisk.org/jira/browse/ASTERISK-26696>]
- pjsip_pubsub: PJSIP Subscription Persistence in AstDB Does not update on
subscription refresh
(Reported by Zach R)
- [ASTERISK-26756 <https://issues.asterisk.org/jira/browse/ASTERISK-26756>]
- res_pjsip_mwi: Asterisk does not terminate MWI subscription
(Reported by Carl Fortin)
- [ASTERISK-26109 <https://issues.asterisk.org/jira/browse/ASTERISK-26109>]
- Asterisk fails building with OpenSSL 1.1.0
(Reported by Tzafrir Cohen)
- [ASTERISK-26723 <https://issues.asterisk.org/jira/browse/ASTERISK-26723>]
- VoiceMailPlayMsg not playing messages via realtime
(Reported by Ryan Rittgarn)
- [ASTERISK-18286 <https://issues.asterisk.org/jira/browse/ASTERISK-18286>]
- [patch] 'Silence' is truncated in Record()
(Reported by var)
- [ASTERISK-26248 <https://issues.asterisk.org/jira/browse/ASTERISK-26248>]
- chan_pjsip: Error when calling PJSIP client with domain specified
(Reported by Norbert Varga)
- [ASTERISK-26788 <https://issues.asterisk.org/jira/browse/ASTERISK-26788>]
- core: Protect flags during ast_waitfor
(Reported by Joshua Colp)
- [ASTERISK-26115 <https://issues.asterisk.org/jira/browse/ASTERISK-26115>]
- pbx: AMI Originate ignore "failed" extension on call failure
(Reported by Nasir Iqbal)
- [ASTERISK-26785 <https://issues.asterisk.org/jira/browse/ASTERISK-26785>]
- configs/samples: The 'identify' entry is in the wrong section in
sorcery.conf.sample
(Reported by Torrey Searle)
- [ASTERISK-26772 <https://issues.asterisk.org/jira/browse/ASTERISK-26772>]
- Crash in srv.c on startup with pjsip
(Reported by nappsoft)
- [ASTERISK-26770 <https://issues.asterisk.org/jira/browse/ASTERISK-26770>]
- res_stasis_device_state: Duplicate subscriptions when multiple received
at same time
(Reported by Joshua Colp)

*Improvements made in this release:*
-----------------------------------
- [ASTERISK-26864 <https://issues.asterisk.org/jira/browse/ASTERISK-26864>]
- res_pjsip_session: Add support for overlap dialling
(Reported by Richard Begg)
- [ASTERISK-26846 <https://issues.asterisk.org/jira/browse/ASTERISK-26846>]
- chan_sip: Add rtcp-mux support
(Reported by Sean Bright)

For a full list of changes in this release, please see the ChangeLog:
http://downloads.asterisk.org/pub/telephony/asterisk/ChangeLog-13.15.0

*Thank you for your continued support of Asterisk!*

----- 13.14.0

The Asterisk Development Team has announced the release of Asterisk 13.14.0.

The release of Asterisk 13.14.0 resolves several issues reported by the
community and would have not been possible without your participation.
Thank you!

The following are the issues resolved in this release:

New Features made in this release:
-----------------------------------
 * ASTERISK-26630 - Make logging PJPROJECT messages a bit easier
      (Reported by Richard Mudgett)

Bugs fixed in this release:
-----------------------------------
 * ASTERISK-26772 - Crash in srv.c on startup with pjsip (Reported
      by nappsoft)
 * ASTERISK-26704 - res_odbc.conf contains deprecated
      configuration: 'pooling', 'shared_connections', 'limit', and
      'idlecheck' options were replaced by 'max_connections'.
      (Reported by Anthony Messina)
 * ASTERISK-21094 - MixMonitorMute mutes through stream if already
      slinear (e.g. Originate) (Reported by David Woolley)
 * ASTERISK-26716 - ari: Channels with pre-dial handlers cannot be
      hung up via ARI (Reported by Tom Pawelek)
 * ASTERISK-26632 - core: Possibility of a frame "imbalance"
      leading to stuck channels. (Reported by Mark Michelson)
 * ASTERISK-25951 - res_agi:  run_agi eats frames it shouldn't
      (Reported by George Joseph)
 * ASTERISK-26343 - ASTERISK-25951 causes issues for callerid
      manipulation through agi (Reported by Morten Tryfoss)
 * ASTERISK-26679 - Crash on invalid contact domain (pjsip aor)
      (Reported by Dmitriy)
 * ASTERISK-26699 - res_pjsip: Assertion when sending OPTIONS
      request  to endpoint (Reported by Ross Beer)
 * ASTERISK-24858 - [patch]Asterisk 13 PJSIP sends RTP packets in
      wrong byte order on Intel platform when using slin codec
      (Reported by Frankie Chin)
 * ASTERISK-26754 - build_tools: make_build_h does not handle \ in
      user name  (Reported by Kirill Katsnelson)
 * ASTERISK-26753 - AMI disconnect causes "ast_careful_fwrite:
      fwrite() returned error: Broken pipe" (Reported by Kirill
      Katsnelson)
 * ASTERISK-26755 - app_queue: Random queues disappear on "core
      reload queue all" (Reported by Kirill Katsnelson)
 * ASTERISK-26735 - res_pjsip_endpoint_identifier_ip: "srv_lookups"
      after match in .conf has no effect (Reported by Michael Maier)
 * ASTERISK-26693 - res_pjsip_endpoint_identifier_ip: Add support
      for SRV (Reported by Joshua Colp)
 * ASTERISK-26743 - PJPROJECT: Detecting compiled max log level
      does not work. (Reported by Richard Mudgett)
 * ASTERISK-26740 - voicemail API test: uses varlibdir instead of
      datadir for a sound file (Reported by Tzafrir Cohen)
 * ASTERISK-26739 - voicemail API test: confuses expected and
      actual values (Reported by Tzafrir Cohen)
 * ASTERISK-26731 - res_sorcery_memory_cache: memory leak on every
      sorcery memory cache populate (Reported by Ustinov Artem)
 * ASTERISK-26710 - [patch] res_rtp_asterisk: CHANNEL arguments,
      (rtcp,all_rtt),(rtcp,all_loss),(rtcp,all_jitter) always return 0
      (Reported by Aaron An)
 * ASTERISK-26672 - Crash when setting remote address on RTP
      instance (Reported by Richard Mudgett)
 * ASTERISK-26670 - [patch] Outgoing SIP-URI Dialing via PJSIP
      (Reported by Alexander Traud)
 * ASTERISK-26691 - Remember SDP negotiation on SIP_CODEC_INBOUND.
      (Reported by Alexander Traud)
 * ASTERISK-26673 - chan_pjsip: Crash when using CHANNEL dialplan
      function around masquerade (Reported by Joshua Colp)
 * ASTERISK-26684 - res_pjsip: Various issues with compact SIP
      headers (Reported by Joshua Elson)
 * ASTERISK-26655 - [patch]pjsip: Transfers Broken with Compact
      Headers Enabled (Reported by JoshE)
 * ASTERISK-26621 - app_queue: Queue application does not ring
      members with Local interface (Reported by Jonas Kellens)
 * ASTERISK-26586 - chan_sip: Segfaults upon reload if client with
      MWI wasn't registered (Reported by Michael Kuron)
 * ASTERISK-25494 - build:  GCC 5.1.x catches some new const, array
      bounds and missing paren issues (Reported by George Joseph)
 * ASTERISK-24499 - Need more explicit debug when PJSIP dialstring
      is invalid (Reported by Rusty Newton)
 * ASTERISK-25083 - Message.c: Message channel becomes saturated
      with frames leading to spammy log messages (Reported by Jonathan
      Rose)
 * ASTERISK-26653 - pjproject_bundled doesn't verify already
      downloaded tarballs (Reported by George Joseph)
 * ASTERISK-26433 - chan_sip: Allows To-tag checks to be bypassed,
      setting up new calls (Reported by Walter Doekes)
 * ASTERISK-26579 - codec_opus: Recursiveness when parsing fmtp
      line (Reported by JÃ¸rgen H)
 * ASTERISK-26644 - PJSIPShowRegistrationsInbound just dumps all
      aors (Reported by George Joseph)
 * ASTERISK-26490 - res_pjsip: sends 481 Call/Transaction Does Not
      Exist when transaction branch parameter contains "_" (Reported
      by Juris Breicis)
 * ASTERISK-26617 - res_rtp_asterisk: Can't bind on systems without
      IPv6 (Reported by Guido Falsi)
 * ASTERISK-24330 - Requirement for 'wss' value in Contact header
      transport parameter on inbound traffic violates RFC7118
      (Reported by Marek Cervenka)
 * ASTERISK-26546 - mips64el and x32 - undefined reference to
      symbol 'dlopen@@GLIBC_2.2' (Reported by Tzafrir Cohen)
 * ASTERISK-26566 - res_rtp_asterisk: RTT miscalculation in RTCP
      (Reported by Hector Royo Concepcion)
 * ASTERISK-26604 - chan_sip: sip reload doesn't apply changes to
      tlscertfile, tlsciphers, etc. (Reported by Michael Kuron)
 * ASTERISK-26603 - [patch] chan_pjsip: not switching sending codec
      to receiving codec when asymmetric_rtp_codec=no (Reported by
      Alexei Gradinari)
 * ASTERISK-26523 - chan_sip: Asterisk 13.12.1 disconnects incoming
      calls after 2 minutes - rtptimeout behaving badly - regression
      (Reported by Michael Keuter)
 * ASTERISK-26503 - app_voicemail: Asterisk crashes when
      MailboxExists is used (Reported by Doug Lytle)

Improvements made in this release:
-----------------------------------
 * ASTERISK-23828 - pjsip - Need a command to list active SIP
      subscriptions (Reported by Rusty Newton)
 * ASTERISK-26527 - Testsuite: increase timeout to check "core
      fullybooted wait" up to 30 sec (Reported by Badalian Vyacheslav)
 * ASTERISK-26624 - res_calendar_caldav: Add support for gmail
      (Reported by Eduardo Scudeller Libardi)
 * ASTERISK-26562 - app_controlplayback: Transmit Silence on
      ControlPlayback pause (Reported by Mikheili Dautashvili)

For a full list of changes in this release, please see the ChangeLog:

http://downloads.asterisk.org/pub/telephony/asterisk/ChangeLog-13.14.0

Thank you for your continued support of Asterisk!

-----