py-softlayer: updated to 5.9.3
[5.9.3] - 2021-03-03

New Commands

slcli file|block disaster-recovery-failover
Improvements

Unit testing for large integers
Add Multi factor authentication to users list
Add pagination to object storage list accounts.
Add username lookup to slcli object-storage credential
Add IOPs data to slcli block volume-list.
Add 2FA and classic APIKeys fields to slcli user list as default values
Add a flags in the report bandwidth
Add the option network component by router to slcli hw create.
Add slcli vs create by router data.
Add testing and support for python 3.9.
Checking for TermLength on prices

[5.9.2] - 2020-12-03

New Commands

slcli account orders
slcli order lookup
Improvements

Ordering price information improvements.
refactor vsi create-option
Add Invoice Item id as parameter in slcli account item-detail command
Added order lookup command to block and file orders.
Add prices to vs create-options.
Allow orders without a location if needed
Refactor file and block commands to use the username resolver
Fix create subnet static for ipv4 price.
moved snapcraft readme
Update snapcraft.yaml
Updated documentation on how to deal with KeyError
Fix order item-list --prices location
Removed Nessus scanner from docs and examples
Fix subnet list.
Fixed analysis/flake8 tests
Remove the -a option from slcli user create. Only the user themselves can create an API key now.
[5.9.1] - 2020-09-15

Fix the ha option for firewalls, add and implement unit test
BluePages_Search and IntegratedOfferingTeam_Region don't need SoftLayer_ prefix
Fix new TOX issues
Add more unit test coverage
Set notes for network storage
Some improvements to the dns commands
dns zone-list: added resourceRecordCount, added automatic pagination for large zones
dns record-list: fixed an issue where a record (like SRV types) that don't have a host would cause the command to fail
Renamed managers.storage.refresh_dep_dupe to SoftLayer.managers.storage.refresh_dupe 1342 to support the new API method. CLI commands now use this method.
added disk upgrade options for virtual guests
[5.9.0] - 2020-08-03

Notification Management
slcli user notifications
slcli user edit-notifications
Added networking options to slcli hw create-options
Refactored slcli hw create to use the ordering manager
Added --network option to slcli hw create for more granular network choices.
Deprecated --port-speed and --no-public . They still work for now, but will be removed in a future release.
Fix Unhandled exception in CLI - vs detail
Fix the empty lines in slcli vs create-options
Ability to list VirtualHost capable guests
slcli hardware guests
slcli vs list will show guests on VirtualHost servers
added option to reload bare metal servers with LVM enabled
Added Migrate command
Added support for filteredMask
Update docs links
Fix lots of whitespace slcli vs create-options
Support for STDIN on creating and updating tickets.
add Drive number in guest drives details using the device number
add vs list hardware and all option
[5.8.9] - 2020-07-06

Automated Snap publisher
Tag Management
slcli tags cleanup
slcli tags delete
slcli tags details
slcli tags list
slcli tags set
slcli tags taggable
Vlan editing functionality
Edit IP note and add ipAddress table in detail view
Subnet Tagging
Storage documentation updates
add system operation referenceCode in create-option
[5.8.8] - 2020-05-18

Fixed ticket upload with REST endpoint
add the redundant/degraded option to hardware
Added iter option for ordering manager functions
Add Account planned, unplanned and announcement events
fixed pylint 2.5.0 errors
Fix AttributeError: 'NoneType' object has no attribute 'keys
Adding more github action tests, removing travis CI tests
fix Response shows additional new lines (\n) in ticket details
Storage feature for virtual and hardware servers
Hardware and Virtual billing info
VPN subnet access to a use
added account billing-items/item-details/cancel-item commands
[5.8.7] - 2020-03-26

Get load balancer (LBaaS) by name
Added version checker
Updated unit test suite for TravisCI to run properly
Add note about using multiple colon symbols not working when setting tags.
Support ordering Dependent Duplicate Volumes
Refactored File/Block managers to reduce duplicated code.
Added Refresh functions for Dependent Duplicate Volumes
Added support for JSON styled parameters and object filters
Added ability to change which datacenters an image template was stored in
[5.8.6] - Skipped

[5.8.5] - 2020-01-29

Fixed an issue with slcli vs dns-sync --ptr. Added slcli hw dns-sync
Fix File Storage failback and failover.
Fix issue where the summary command fails due to None being provided as the datacenter name.
Added The following commands:
slcli block volume-limits
slcli file volume-limits
Add testing/CI for python 3.8.
Fix vs detail erroring on servers pending cancellation.
support subnet ACL management through cli
slcli block subnets-list
slcli block subnets-assign
slcli block subnets-remove
Added documentation for all SLCLI commands.
[5.8.4] - 2019-12-20

Fix block storage failback and failover.
Order a virtual server private.
[5.8.3] - 2019-12-11

Fixed unicode errors in image list (for windows)
Fixed ordering virtual server dedicated from the CLI
Fixed capacity restriction when ordering storage quotes
Fixed hardware detail bandwidth allocation errors.
[5.8.2] - 2019-11-15

Fixed a unit test that could fail if the test took too long to run.
Added a check to ensure subnet and vlan options are properly added to the order for virtual servers.
Fixed a readme misspelling.
Fixed vs reboot unable to resolve vs names.
Handle missing Fixtures better for unit tests.
[5.8.1] - 2019-10-11

Drop python 2.7 support
Added CS# to ticket listing
Fixed issue looking up OS keyName instead of referenceCode
Autoscale support
slcli autoscale detail
slcli autoscale edit
slcli autoscale list
slcli autoscale logs
slcli autoscale scale
slcli autoscale tag
[5.8.0] - 2019-09-04

Upgrade to prompt_toolkit >= 2
Bandwidth Feature
slcli summary
slcli report bandwidth
slcli vs bandwidth
slcli hw bandwidth
Added bandwidth to VS and HW details page
DOCS: replace 'developer' with 'sldn' links
property 'contents' is not valid for 'SoftLayer_Ticket' when creating a ticket
cannot create static subnet with slcli
Refactor cdn network.
IBMID auth support
Transient VSI support
Removed legacy LoadBalancer command, added Citrix and IBM LBaaS commands.
slcli lb cancel
slcli lb detail
slcli lb health
slcli lb l7pool-add
slcli lb l7pool-del
slcli lb list
slcli lb member-add
slcli lb member-del
slcli lb ns-detail
slcli lb ns-list
slcli lb order
slcli lb order-options
slcli lb pool-add
slcli lb pool-del
slcli lb pool-edit
Remove VpnAllowedFlag.
Improve hardware cancellation to deal with additional cases
[5.7.2] - 2019-05-03

Added exception to handle json parsing error when ordering
Support for -1 when changing port speed
Fixed docs about placement groups
File storage endurance iops upgrade
Handle the new user creation exceptions
Fix order place quantity option
Invoice commands
account invoices
account invoice-detail
account summary
Event Notification Management commands
account events
account event-detail
Two PCIe items can be added at order time
Fix object storage apiType for S3 and Swift.
Event Log performance improvements.
column 'name' was renamed to 'hostname'
Fix object storage credentials.
Fixed unexpected errors in slcli subnet create
Change encrypt parameters for importing of images. Adds root-key-crn
Quote ordering commands
order quote
order quote-detail
order quote-list
VS usage information command
virtual usage
made sure config_tests dont actually make api calls.
[5.7.1] - 2019-02-26

removed legacy SL message queue commands
Support for Hardware reflash firmware CLI/Manager method
[5.7.0] - 2019-02-15

Support for security group Ids
event-log cli command
Virtual Placement Group Support
   slcli vs placementgroup --help
 Commands:
   create          Create a placement group.
   create-options  List options for creating a placement group.
   delete          Delete a placement group.
   detail          View details of a placement group.
   list            List placement groups.
Rest Transport improvements. Properly handle HTTP exceptions instead of crashing.
removed power_state column option from "slcli server list"
- ipv6 support for creating virtual guests
Refactored virtual guest creation to use Product_Order::placeOrder instead of Virtual_Guest::createObject, because createObject doesn't allow adding IPv6
Added table which shows the status of each url in object storage
Update provisionedIops reading to handle float-y values
fixed issue with config setup
Fix file volume-cancel
Support for SoftLayer_Hardware_Server::toggleManagementInterface
slcli hw toggle-ipmi