py-pylint: updated to 2.17.4
2.17.4

False Positives Fixed

Fix a false positive for bad-dunder-name when there is a user-defined
__index__ method.

Other Bug Fixes

pyreverse: added escaping of vertical bar character in annotation labels
produced by DOT printer to ensure it is not treated as field separator of
record-based nodes.

Fixed a crash when generating a configuration file:
tomlkit.exceptions.TOMLKitError: Can't add a table to a dotted key
caused by tomlkit v0.11.8.