kew: set GCC_REQD=8
With gcc 7, this throws
error: initializer element is not constant
doesn't matter what C standard is set with -std; works fine with gcc 8.