py-werkzeug: updated to 0.15.5
Version 0.15.5
- Fix a TypeError due to changes to ast.Module in Python 3.8.
- Fix a C assertion failure in debug builds of some Python 2.7
  releases.
- :class:~exceptions.BadRequestKeyError adds the KeyError
  message to the description if e.show_exception is set to
  True. This is a more secure default than the original 0.15.0
  behavior and makes it easier to control without losing information.
- Upgrade the debugger to jQuery 3.4.1.
- Work around an issue in some external debuggers that caused the
  reloader to fail.
- Work around an issue where the reloader couldn't introspect a
  setuptools script installed as an egg.
- The reloader will use sys.executable even if the script is
  marked executable, reverting a behavior intended for NixOS
  introduced in 0.15. The reloader should no longer cause
  OSError: [Errno 8] Exec format error.
- SharedDataMiddleware safely handles paths with Windows drive
  names.