net/tor: Workaround upstream "micro-revision.i" bug
There is something wrong in tor's  makefiles which causes:

  src/lib/version/git_revision.c:21:10: fatal error: micro-revision.i: No such file or directory
   #include "micro-revision.i"
	    ^~~~~~~~~~~~~~~~~~
  compilation terminated.

obviously by not having built micro-revision.i when that compilation
is done.   This happens reliably for some people and not for others.

This commit adds a comment with the issue in tor's bug tracker, and a
workaround that builds micro-revision.i and then does the normal
build.

No PKGREVISION as this is just a build fix, and should have zero
effect if this built anyway.

ok @wiz