Update converters/unoconv to 0.8.2
Changes since 0.7

Implemented enhancements:

    Update README.adoc #370 (Atalanttore)
    Add a command line option to specify import filter name #343 (MartijnVdS)
    manage office exit code 81 on listener #327 (alikefia)
    Typo in manpage #313 (jacobmischka)
    Handle SIGTERM when starting as listener #301 (leture)
    Add .travis.yml to run tests from 3.3 to 5.0 on OS X and Linux #296 (pquentin)
    fix misset printer for drawing #294 (wmin0)
    add printer options #282 (wmin0)
    Add extra bin/lib directories for LibreOffice on OS X #276 (hubgit)

Fixed bugs:

    Ambiguous message #326
    Fix travis downloads #314 (pquentin)
    Fix for Python 3 to read binary data from stdin #309 (kaysersoze)

Closed issues:

    failed to replace variable 'A' with value 'B' in the document. #425
    Add more maintainers #411
    PPT changing color while converting with Unoconv #406
    ERROR: No module named 'uno' #403
    unoconv from pptx, text is rendered as image #401
    Compare docs #400
    Unoconv creates new file with root permissions #394
    xsl:attribute: Cannot add attributes to an element if children have been already added to the element. #387
    Output file is owned by root #381
    PPT to PDF: Textboxes underneath images appearing on top of image #378
    script works fine with CLI but do not work with browser #365
    Problem to execute from PHP (Ubuntu, XAMPP) #353
    Progress bar #346
    Can't get remote listener to work #341
    Can't run unoconv as www-data user in Ubuntu 14.04LTS #336
    Segmentation fault on Alpine Linux #333
    Some docx files that contained table does not be converted to pdf exactly #330
    Can not convert ppt file to pdf file with file name which contain japanese character. #325
    How to install latest unoconv from github into ubuntu 14.40 headless terminal? #323
    mac osx + emf conversion delegates to imagemagick which doesnt support it #320
    Unable to use unoconv through php shell_exec #302
    Running 2+ instances of unoconv concurrently results in error #299
    Missing help option in help output #297
    OS X, LibreOffice 4.4 and 5.0: no suitable office installation #292
    Enhancing the performance on converting text files #291
    Cannot find a suitable pyuno library and python binary combination in /usr/lib/libreoffice #290
    Conversion of a list from a docx to html #287
    unoconv 0.7 hangs out of nowhere #274
    pagination #268
    LibreOffice Python Syntax Error Mac OS X #166

Merged pull requests:

    * make -F switch working for user-defined fields #426 (belegnar)
    Updated Changelog and docs #422 (regebro)
    Added setup.py #421 (regebro)
    Drop support for v3.3 and v3.4 #413 (regebro)
    pass the password as openoffice expects it, so it will work for docum# #358 (monomelodies)