py-test: updated to 3.8.1
pytest 3.8.1:

Bug Fixes
* .pytest_cache directory is now automatically ignored by Git. Users who would like to contribute a solution for other SCMs please consult/comment on this issue.
* Fix the following error during collection of tests inside packages:
  TypeError: object of type 'Package' has no len()
* Fix bug where indirect parametrization would consider the scope of all fixtures used by the test function to determine the parametrization scope, and not only the scope of the fixtures being parametrized.
* Fix crash of the assertion rewriter if a test changed the current working directory without restoring it afterwards.
* Fix issue that prevented some caplog properties (for example record_tuples) from being available when entering the debugger with --pdb.
* Fix UnicodeDecodeError in python2.x when a class returns a non-ascii binary __repr__ in an assertion which also contains non-ascii text.

Improved Documentation
* New Deprecations and Removals page shows all currently deprecated features, the rationale to do so, and alternatives to update your code. It also list features removed from pytest in past major releases to help those with ancient pytest versions to upgrade.

Trivial/Internal Changes
* Improve pre-commit detection for changelog filenames
* Remove legacy code around im_func as that was python2 only