Update to Asterisk 14.1.0: this is mostly a bug fix release.
The Asterisk Development Team has announced the release of Asterisk 14.1.0.

The release of Asterisk 14.1.0 resolves several issues reported by the
community and would have not been possible without your participation.
Thank you!

The following are the issues resolved in this release:

New Features made in this release:
-----------------------------------
 * ASTERISK-26277 - Add dialplan function
      PJSIP_SEND_SESSION_REFRESH that sends a session refresh to
      update formats on a channel after session establishment
      (Reported by Matt Jordan)

Bugs fixed in this release:
-----------------------------------
 * ASTERISK-26477 - pjproject:  SEGV during SSL operations
      (Reported by George Joseph)
 * ASTERISK-17470 - [patch] - When videosupport=yes, asterisk
      allows one end peer to send video, even though the other end
      supports only audio. (Reported by effie mouzeli)
 * ASTERISK-26416 - pjproject-bundled: configure fails to check for
      all required utilities (Reported by Corey Farrell)
 * ASTERISK-26466 - core: Be forgiving on external callerid that
      may be flawed so we don't drop events (Reported by Richard
      Mudgett)
 * ASTERISK-26362 - res_config_mysql:  Broken after 13.10 (Reported
      by Carlos Chavez)
 * ASTERISK-26446 - app_dial:  There's no way to override the
      hangupcause on unanswered channels (Reported by George Joseph)
 * ASTERISK-26410 - core: Asterisk 14 doesn't show the header in
      the console or verbose when starting (Reported by Dan Jenkins)
 * ASTERISK-24311 - Populating database via Alembic fails when
      using same database for multiple schema sets (Reported by Dafi
      Ni)
 * ASTERISK-26438 - [patch] chan_sip: auto_force_rport: No NAT = No
      Symmetric Response. (Reported by Alexander Traud)
 * ASTERISK-26426 - format_ogg_opus: remove from source (Reported
      by Kevin Harwell)
 * ASTERISK-18232 - Broken REGISTER sent to IPv4 server when
      bindaddr=[::] (Reported by Jacek)
 * ASTERISK-25468 - Deadlock in chan_sip - core show locks shows
      do_monitor lock (Reported by Barry Flanagan)
 * ASTERISK-26397 - manager: PresenceState action crashes Asterisk
      14 (Reported by Andrew Nagy)
 * ASTERISK-26389 - res_odbc: Clean up pooling options (Reported by
      Joshua Colp)
 * ASTERISK-26359 - [patch] cdr_mysql: fails to use UTC if so
      instructed (Reported by Tzafrir Cohen)
 * ASTERISK-26273 - core: Won't compile when LOW_MEMORY is enabled
      (Reported by Anthony Messina)
 * ASTERISK-26391 - Consoles do not display verbose logger messages
      even when requested. (Reported by Marcelo Terres)
 * ASTERISK-26263 - SQL error when using realtime and registering
      extension / inserting into ps_contacts (Reported by Jeppe Ryskov
      Larsen)
 * ASTERISK-26365 - rtp: Offer with multiple payloads for same
      codec is incorrectly handled (Reported by Joshua Colp)
 * ASTERISK-19968 - TCP Session-Timers not dropping call (Reported
      by Aaron Hamstra)
 * ASTERISK-26374 - res_pjsip_multihomed: Contact port is rewritten
      for connectionful protocols (Reported by Joshua Colp)
 * ASTERISK-26367 - rtp: Timestamps broken when video frame is
      across multiple RTP packets (Reported by Joshua Colp)
 * ASTERISK-26375 - res_pjsip_transport_management: Log message
      states seconds, but time value is milliseconds (Reported by
      Joshua Colp)
 * ASTERISK-26364 - res_pjsip: Don't assume a request will have
      target addresses (Reported by Joshua Colp)
 * ASTERISK-26360 - app_queue: "queue show" output gets "failed to
      extend from 240 to 327" msgs. (Reported by Richard Mudgett)
 * ASTERISK-26316 - res_pjsip_callerid: Irregular URI causes
      unexpected callerid (Reported by Kevin Harwell)
 * ASTERISK-26349 -  13.11.1 res_pjsip/pjsip_distributor.c: Request
      'REGISTER' failed (Reported by Dmitry Melekhov)
 * ASTERISK-26272 - chan_sip: File descriptors leak (UDP sockets)
      (Reported by Etienne Lessard)
 * ASTERISK-26264 - res_pjsip: Crash when applying ACL from
      non-existent endpoint (Reported by nappsoft)
 * ASTERISK-26341 - ARI: Stopping a media playlist only stops the
      current media URI being played back, and not the whole list
      (Reported by Matt Jordan)
 * ASTERISK-25691 - Crash occurs when screening mode (Dial's 'p'
      argument) is enabled and callee rejects a call or hangs up.
      (Reported by Etienne Lessard)
 * ASTERISK-26331 - Crash on "core show channeltype Surrogate" in
      ast_format_cap_get_names (Reported by CGI.NET)
 * ASTERISK-26269 - res_pjsip: Wrong state for aors without
      registered contacts after startup (Reported by nappsoft)
 * ASTERISK-26282 - AEL: macro-call in Dial application, macro
      "lacks 's' extension" (Reported by chris de rock)
 * ASTERISK-26226 - pbx: Asterisk crash on AMI action
      "ShowDialplan" when there's a circular dependency between
      contexts (Reported by Etienne Lessard)
 * ASTERISK-26299 - app_queue: Queue application sometimes stops
      calling members with Local interface (Reported by Etienne
      Lessard)
 * ASTERISK-26279 - pjproject-bundled:  Fails to compile on Debian
      6 (Reported by George Joseph)
 * ASTERISK-26306 - channel: Hang-up crashes, chan_pjsip not
      cleaning up properly (Reported by Alexander Traud)
 * ASTERISK-26203 - res_fax: Deadlock when using
      FAXOPT(gateway)=yes with Local channels (Reported by Etienne
      Lessard)
 * ASTERISK-24822 - Deadlock: Fax Gateway framehook creates locking
      inversion in T.38 query option with features bridging code
      (Reported by David Brillert)
 * ASTERISK-22732 - Deadlock potential in res_fax and CCSS with
      local channels. (Reported by Richard Mudgett)
 * ASTERISK-26288 - followme: fails to reset config items to
      default values on reload (Reported by Tzafrir Cohen)
 * ASTERISK-22374 - Finish mapping the sip.conf parameters to
      res_sip.conf parameters (Reported by Matt Jordan)
 * ASTERISK-24425 - [patch] jabber/xmpp to use TLS instead of
      SSLv3, security fix POODLE (CVE-2014-3566) (Reported by
      abelbeck)
 * ASTERISK-26228 - res_pjsip_sdp_rtp: G729A does not include
      annexb=no attribute. (Reported by Ali Ghavidel)
 * ASTERISK-25472 - Swagger scripts are not replacing format
      variable in file brief (Reported by Corey Farrell)
 * ASTERISK-25984 - res_odbc relies on res_odbc_transaction, but
      it's not mandatory to compile it (Reported by József Dudás)
 * ASTERISK-26305 - Asterisk 14: Two resolver unbound testsuite
      tests fail (Reported by Richard Mudgett)
 * ASTERISK-26303 - [patch] BuildSystem: ca_list_path capabilities
      not detected in PJProject. (Reported by Alexander Traud)
 * ASTERISK-25492 - ARI: Path parameters are case sensitive
      (Reported by Joshua Colp)
 * ASTERISK-26164 - XMPP no longer triggers NOTIFY to device via
      chan_pjsip (Reported by Ross Beer)
 * ASTERISK-26233 - pbx: Failure to remove inconsistent extension
      names (Reported by Corey Farrell)
 * ASTERISK-26246 - Security: Privilege escalation by AMI adding
      dialplan extensions. (Reported by Richard Mudgett)
 * ASTERISK-26267 - ast_register_atexit callbacks should be run on
      failed startup. (Reported by Corey Farrell)
 * ASTERISK-26241 - res_pjsip:  When using compact headers, rpid
      and pai are incorrectly generated (Reported by George Joseph)
 * ASTERISK-25797 - app_queue: Crash when calling a queue with a
      member with a forward to an nonexistent extension (Reported by
      Etienne Lessard)
 * ASTERISK-26239 - res_pjsip_logger:  An empty global/debug option
      is treated as a "match all" hostname (Reported by George Joseph)
 * ASTERISK-26238 - res_pjsip: Empty global default_from_user
      causes crash (Reported by Joshua Colp)
 * ASTERISK-26268 - alembic: 'auth_username' not in PJSIP
      'identify_by' enum (Reported by Joshua Colp)
 * ASTERISK-26253 - sdp_srtp: libsrtp now a required dependency,
      shouldn't be (Reported by Ben Merrills)
 * ASTERISK-26145 - pjsip: Deadlock with suspend + masquerade +
      indicate (Reported by Ross Beer)
 * ASTERISK-26183 - alembic: error when using sqlalchemy version
      1.1.0b2 (Reported by Kevin Harwell)
 * ASTERISK-26283 - res_resolver_unbound:  fails configure on older
      Ubuntu and CentOS (Reported by George Joseph)
 * ASTERISK-26280 - DNS lookups can block channel media paths
      (Reported by Mark Michelson)
 * ASTERISK-26278 - asterisk.h should produce a reasonable error
      for external modules that fail to define AST_MODULE_SELF_SYM.
      (Reported by Corey Farrell)
 * ASTERISK-25217 - [patch]res_pjsip_outbound_publish.c needs a
      similar treatment for module unloading as
      res_pjsip_outbound_registration.c (Reported by Richard Mudgett)
 * ASTERISK-26265 - Errors ignored from some parts of system
      initialization. (Reported by Corey Farrell)
 * ASTERISK-26206 - [patch] res_pjsip: Use more compatible regex
      for get all (Reported by Dmitry)
 * ASTERISK-26256 - [patch] SIP/SDP origin (o=) contains brackets
      with IP6 (Reported by Alexander Traud)
 * ASTERISK-25996 - Remove "live_dangerously" requirement on
      DB(read) (Reported by Andrew Nagy)
 * ASTERISK-26148 - pjsip: Cannot compile 13.10.0-rc1:
      "libasteriskpj.so: undefined reference to..." (Reported by Hans
      van Eijsden)
 * ASTERISK-26237 - Fax is detected on regular calls. (Reported by
      Richard Mudgett)

Improvements made in this release:
-----------------------------------
 * ASTERISK-26409 - codec_opus: Update Asterisk to support the
l
      translation codec. (Reported by Kevin Harwell)
 * ASTERISK-26289 - Announcer channels in ConfBridges cause
      inefficiencies (Reported by Mark Michelson)
 * ASTERISK-25980 - [patch]res_fax: set FAXMODE variable to let
      dialplan know what fax transport was used (Reported by Alexei
      Gradinari)

For a full list of changes in this release, please see the ChangeLog:

http://downloads.asterisk.org/pub/telephony/asterisk/ChangeLog-14.1.0

Thank you for your continued support of Asterisk!